//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;
using prankard.extensions.sound.api.vo;
using prankard.extensions.sound.api.model;
using System.ComponentModel;
using robotlegs.bender.framework.api;


namespace prankard.extensions.sound.impl.model
{
	public class SoundModel : ISoundModel
	{
		private static readonly SoundVO NULL_SOUND = new SoundVO("null", null);

		private List<SoundVO> soundEffects = new List<SoundVO>();
		private List<SoundVO> musicTracks = new List<SoundVO>();

		[Inject]
		public ILogging logger;
		
		public void AddSoundEffects(SoundVO[] soundVOs)
		{
			soundEffects.AddRange(soundVOs);
		}
		
		public void AddMusicTracks(SoundVO[] soundVOs)
		{
			musicTracks.AddRange(soundVOs);
		}
		
		public SoundVO GetSoundEffect(string name)
		{
			foreach (SoundVO sound in soundEffects)
			{
				if (sound.name == name)
				{
					return sound;
				}
			}
			logger.Warn ("Could not find sound effect: '{0}'", name);
			return NULL_SOUND;
		}
		
		public SoundVO GetMusicTrack(string name)
		{
			foreach (SoundVO sound in musicTracks)
			{
				if (sound.name == name)
				{
					return sound;
				}
			}
			logger.Warn ("Could not find music track: '{0}'", name);
			return NULL_SOUND;
		}
		
		public float SoundVolume
		{
			get
			{
				return PlayerPrefs.GetFloat("sound_volume", 1);
			}
			set
			{
				PlayerPrefs.SetFloat("sound_volume", value);
			}
		}
		
		public float MusicVolume
		{
			get
			{
				return PlayerPrefs.GetFloat("music_volume", 1);
			}
			set
			{
				PlayerPrefs.SetFloat("music_volume", value);
			}
		}
	}
}

