//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.extensions.mediatorMap.api;


namespace prankard.extensions.sound.api.view
{
	public interface ISoundSetView : IEventView
	{
		void UpdateSoundEffectsVolume(float volume);
		void UpdateMusicVolume(float volume);
	}
}

