//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

using Robotlegs.Bender.Platforms.Unity.Extensions.Mediation.Impl;
using prankard.extensions.sound.api.vo;


namespace prankard.extensions.sound.api.view
{
	public class SoundLoaderView : EventView
	{
		public SoundVO[] soundEffects;
		public SoundVO[] musicTracks;

		protected override void Start ()
		{
			Debug.Log("Start SoundLoaderView");
			base.Start();
		}
	}
}

