//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;


namespace prankard.extensions.sound.api.vo
{
	[Serializable]
	public struct SoundVO
	{
		public string name;
		public AudioClip audio;

		public SoundVO (string name, AudioClip audio)
		{
			this.name = name;
			this.audio = audio;
		}
	}
}

