//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

using robotlegs.bender.platforms.unity.extensions.mediatorMap.impl;
using UnityEngine.UI;


namespace prankard.extensions.sound.impl.view
{
	[RequireComponent(typeof(Image))]
	public class SoundToggleView : EventView
	{
		private Image image;

		[SerializeField] private Sprite onSprite;
		[SerializeField] private Sprite offSprite;

		private bool _on = false;
		public bool On
		{
			get
			{
				return _on;
			}
		}

		protected override void Start ()
		{
			image = GetComponent<Image>();
			base.Start ();
		}

		public void Toggle()
		{
			Toggle(!_on);
		}
		
		public void Toggle(bool on)
		{
			_on = on;
			UpdateGraphics();
		}

		public void UpdateGraphics()
		{
			image.sprite = _on ? onSprite : offSprite;
		}
	}
}

