//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.extensions.mediatorMap.api;
using prankard.extensions.sound.api.view;
using prankard.extensions.sound.api.model;


namespace prankard.extensions.sound.impl.view.mediator
{
	public class SoundLoaderMediator : IMediator
	{
		[Inject]
		public ISoundModel soundModel {get;set;} // TODO: Make this not inject into the mediator, but dispatch events

		[Inject]
		public SoundLoaderView view {get;set;}

		public void Initialize ()
		{
			UnityEngine.Debug.Log ("Init");
			soundModel.AddSoundEffects(view.soundEffects);
			soundModel.AddMusicTracks(view.musicTracks);
		}

		public void Destroy ()
		{

		}
	}
}

