//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.extensions.eventDispatcher.api;
using robotlegs.bender.extensions.mediatorMap.api;
using prankard.extensions.sound.api.events;
using prankard.extensions.sound.api.model;
using prankard.extensions.sound.api.view;


namespace prankard.extensions.sound.impl.view.mediator
{
	public class SoundSetMediator : IMediator
	{
		[Inject]
		public IEventDispatcher dispatcher {get;set;}

		[Inject]
		public ISoundSetView view {get;set;}

		[Inject]
		public ISoundModel model {get;set;} //TODO: Make this not inject here!!!

		public void Initialize ()
		{
			view.dispatcher.AddEventListener(SoundVolumeEvent.Type.SET_MUSIC_VOLUME, dispatcher.Dispatch);
			view.dispatcher.AddEventListener(SoundVolumeEvent.Type.SET_SOUND_EFFECTS_VOLUME, dispatcher.Dispatch);

			view.UpdateMusicVolume(model.MusicVolume);
			view.UpdateSoundEffectsVolume(model.SoundVolume);
		}

		public void Destroy ()
		{
			view.dispatcher.RemoveEventListener(SoundVolumeEvent.Type.SET_MUSIC_VOLUME, dispatcher.Dispatch);
			view.dispatcher.RemoveEventListener(SoundVolumeEvent.Type.SET_SOUND_EFFECTS_VOLUME, dispatcher.Dispatch);
		}
	}
}

